config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/urls/new')
  resources :urls
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
    validates :original, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all
  end

  def show
    url = Url.where(:random_id=>params[:id]).first

    if url
      redirect_to url.original
    else
      render "index"
    end
  end

  def new
    @url = Url.new
    letters = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    @url.random_id = (0...8).map{ letters[rand(letters.length)] }.join
  end

  def urls_params
    params.require(:url).permit(:original, :random_id)
  end

  def create
    @url = Url.new(urls_params)

    if @url.save
      redirect_to urls_path
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLshortener</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>Urly URLS</h1>
<% @urls.each do |url| %>
    <p>
    <%= link_to url.random_id, url_path(:id => url.random_id) %> => <%= url.original %>
    </p>
<% end %>

<%= link_to "Shorten another URL", new_url_path %>

app/views/urls/new.html.erb
<h1>Shorten URL</h1>

<% @url.errors.each do |attr, msg| %>
    <%= msg %> on <%= attr %>
<% end %>


<%= form_for @url do |f| %>
    <p>
    <%= f.label :original %> : <%= f.text_field :original %>
    </p>
    <p>
      <%= f.hidden_field :random_id, :value => @url.random_id  %>
      <%= f.submit "Shorten my URL" %>
    </p>

<% end %>